#local dev env only
services:
  app:
    build: .
    container_name: nusci-backend-2
    env_file:
      - .env
    command: npm start
    depends_on:
      - mongodb
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/app
  mongodb:
    image: mongo
    container_name: nusci-database-2
    env_file:
      - .env
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
    ports:
      - ${MONGODB_INITDB_PORT}:${MONGODB_INITDB_PORT}
    volumes:
      - ./.database:/data/db
