import mongoose from "mongoose";
import Accounts from "../../api/models/enums/accounts.js";

export default [
  {
    title: "Meeting with Team",
    description: "Discuss project progress",
    startTime: new Date("2024-05-10T09:00:00"),
    endTime: new Date("2024-05-10T10:00:00"),
    location: "Conference Room A",
    public: true,
    visibleToRoles: [Accounts.Author.role, Accounts.Editor.role],
    associatedWithRoles: [Accounts.Author.role, Accounts.Editor.role],
    creatingUser: new mongoose.Types.ObjectId(),
    creationTime: new Date(),
    modificationTime: new Date(),
  },
  {
    title: "Club Holiday Party",
    description: "Celebrate the holiday season with the team",
    startTime: new Date("2024-12-20T18:00:00"),
    endTime: new Date("2024-12-20T22:00:00"),
    location: "NUSci office (rip)",
    public: true,
    visibleToRoles: [Accounts.Photographer.role, Accounts.Developer.role],
    associatedWithRoles: [Accounts.Photographer.role, Accounts.Developer.role],
    creatingUser: new mongoose.Types.ObjectId(),
    creationTime: new Date(),
    modificationTime: new Date(),
  },
  {
    title: "Monthly Team Meeting",
    description: "Monthly review and planning meeting",
    startTime: new Date("2024-06-15T09:00:00"),
    endTime: new Date("2024-06-15T10:30:00"),
    location: "Boardroom",
    public: true,
    visibleToRoles: [Accounts.Author.role, Accounts.Editor.role],
    associatedWithRoles: [Accounts.Author.role, Accounts.Editor.role],
    creatingUser: new mongoose.Types.ObjectId(),
    creationTime: new Date(),
    modificationTime: new Date(),
  },
  {
    title: "Product Launch Event",
    description: "Launch event for our latest product",
    startTime: new Date("2024-09-30T18:00:00"),
    endTime: new Date("2024-09-30T21:00:00"),
    location: "Convention Center",
    public: true,
    visibleToRoles: [Accounts.Developer.role, Accounts.Admin.role],
    associatedWithRoles: [Accounts.Developer.role, Accounts.Admin.role],
    creatingUser: new mongoose.Types.ObjectId(),
    creationTime: new Date(),
    modificationTime: new Date(),
  },
];
