export default [
  {
    username: "ethan",
    role: "admin",
    email: "ethan@ethan.com",
    password: "1",
    information: {
      year: 2026,
      major: "Computer Science and Mathematics",
      bio: "Co-Head of Web & Software with Raisa",
      image: "url.com",
    },
  },
  {
    username: "raisa",
    role: "admin",
    email: "raisa@raisa.com",
    password: "1",
    information: {
      year: 2025,
      major: "Computer Science and Mathematics",
      bio: "Co-Head of Web & Software with Ethan",
      image: "url.com",
    },
  },
  {
    username: "sutton",
    role: "developer",
    email: "sutton@sutton.com",
    password: "1",
    information: {
      year: 2026,
      major: "Computer Science",
      bio: "Teaching & Technical Assistant",
      image: "url.com",
    },
  },
  {
    username: "arushi",
    role: "developer",
    email: "arushi@arushi.com",
    password: "1",
    information: {
      year: 2027,
      major: "Computer Science",
      bio: "Teaching & Technical Assistant",
      image: "url.com",
    },
  },
  {
    username: "jiajia",
    role: "photographer",
    email: "jiajia@jiajia.com",
    password: "1",
    information: {
      year: 2026,
      major: "Bioengineering",
      bio: "Awesome photographer",
      image: "url.com",
    },
  },
  {
    username: "noah",
    role: "editor",
    email: "noah@noah.com",
    password: "1",
    information: {
      year: 2024,
      major: "Applied Physics",
      bio: "Best editor-in-chief",
      image: "url.com",
    },
  },
  {
    username: "nethra",
    role: "editor",
    email: "nethra@nethra.com",
    password: "1",
    information: {
      year: 2024,
      major: "Chemical Engineering",
      bio: "Good editor, perhaps",
      image: "url.com",
    },
  },
  {
    username: "vianna",
    role: "author",
    email: "vianna@vianna.com",
    password: "1",
    information: {
      year: 2025,
      major: "Pharmaceutical Science",
      bio: "Good author, awesome designer",
      image: "url.com",
    },
  },
  {
    username: "jasmine",
    role: "author",
    email: "jasmine@jasmine.com",
    password: "1",
    information: {
      year: 2025,
      major: " SBehavioral Neuroscience",
      bio: "Not an author but I couldn't think of anyone else",
      image: "url.com",
    },
  },
];
