import mongoose from "mongoose";
import Accounts from "../../api/models/enums/accounts.js";
import AccountStatus from "../../api/models/enums/account_status.js";
import { ObjectId } from "mongodb";

export default [
  {
    _id: new ObjectId("71fb08439addd8acb14aa754"),
    firstName: "John",
    lastName: "Doe",
    username: "johndoe",
    pronouns: ["he", "him"],
    graduationYear: 2023,
    majors: ["Computer Science"],
    location: "New York",
    profileImage: "https://example.com/profile.jpg",
    bannerImage: "https://example.com/banner.jpg",
    bio: "Software developer",
    emails: ["johndoe@example.com"],
    phone: "1234567890",
    roles: [Accounts.Author.role, Accounts.Editor.role],
    status: AccountStatus.Approved.status,
    //approvingUser: new mongoose.Types.ObjectId(),
    //gameData: new mongoose.Types.ObjectId(),
    creationTime: new Date(),
    modificationTime: new Date(),
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    username: "janesmith",
    pronouns: ["she", "her"],
    graduationYear: 2022,
    majors: ["Engineering"],
    location: "Los Angeles",
    profileImage: "https://example.com/janesmith.jpg",
    bannerImage: "https://example.com/janesmith_banner.jpg",
    bio: "Mechanical engineer",
    emails: ["janesmith@example.com"],
    phone: "0987654321",
    roles: [Accounts.Photographer.role, Accounts.Developer.role],
    status: AccountStatus.Approved.status,
    approvingUser: new mongoose.Types.ObjectId(),
    gameData: new mongoose.Types.ObjectId(),
    creationTime: new Date(),
    modificationTime: new Date(),
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    username: "alicejohnson",
    pronouns: ["she", "her"],
    graduationYear: 2024,
    majors: ["Biology"],
    location: "Chicago",
    profileImage: "https://example.com/alicejohnson.jpg",
    bannerImage: "https://example.com/alicejohnson_banner.jpg",
    bio: "Biologist",
    emails: ["alicejohnson@example.com"],
    phone: "1357924680",
    roles: [Accounts.Author.role],
    status: AccountStatus.Pending.status,
    approvingUser: null,
    gameData: null,
    creationTime: new Date(),
    modificationTime: new Date(),
  },
  {
    firstName: "Mark",
    lastName: "Brown",
    username: "markbrown",
    pronouns: ["he", "him"],
    graduationYear: 2025,
    majors: ["Marketing"],
    location: "Miami",
    profileImage: "https://example.com/markbrown.jpg",
    bannerImage: "https://example.com/markbrown_banner.jpg",
    bio: "Marketing specialist",
    emails: ["markbrown@example.com"],
    phone: "9876543210",
    roles: [Accounts.Editor.role],
    status: AccountStatus.Deactivated.status,
    approvingUser: new mongoose.Types.ObjectId(),
    gameData: new mongoose.Types.ObjectId(),
    creationTime: new Date(),
    modificationTime: new Date(),
  },
];
