name: Build Project and Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Docker manually (Docker is already pre-installed on ubuntu-latest)
      - name: Set up Docker
        run: sudo apt-get update && sudo apt-get install -y docker

      # Step 3: Set up Docker Compose
      - name: Set up Docker Compose
        run: sudo apt-get install -y docker-compose

      # Step 4: Build and Start Docker Compose with secrets as environment variables
      - name: Create .env File Securely and Start Docker Compose
        run: |
          cat <<EOF > .env
          SERVER_HOSTNAME=${{ vars.SERVER_HOSTNAME }}
          SERVER_PORT=${{ vars.SERVER_PORT }}
          SERVER_TOKEN_KEY=${{ vars.SERVER_TOKEN_KEY }}
          MONGODB_INITDB_ROOT_USERNAME=${{ vars.MONGODB_INITDB_ROOT_USERNAME }}
          MONGODB_INITDB_ROOT_PASSWORD=${{ vars.MONGODB_INITDB_ROOT_PASSWORD }}
          MONGODB_INITDB_HOSTNAME=${{ vars.MONGODB_INITDB_HOSTNAME }}
          MONGODB_INITDB_PORT=${{ vars.MONGODB_INITDB_PORT }}
          EOF
          docker-compose --env-file .env up --build -d

      # Step 5: Run any commands you want (e.g., tests)
      - name: Run Tests
        run: |
          docker exec nusci-backend npm run test

      # Step 6: Tear down the services after the job is done
      - name: Tear Down Docker Compose
        if: always()
        run: docker-compose down
