name: Build Project and Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          "SERVER_HOSTNAME=${{ vars.SERVER_HOSTNAME }}" >> .env
          "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
          "SERVER_TOKEN_KEY=${{ vars.SERVER_TOKEN_KEY }}" >> .env
          "MONGODB_INITDB_ROOT_USERNAME=${{ vars.MONGODB_INITDB_ROOT_USERNAME }}" >> .env
          "MONGODB_INITDB_ROOT_PASSWORD=${{ vars.MONGODB_INITDB_ROOT_PASSWORD }}" >> .env
          "MONGODB_INITDB_HOSTNAME=${{ vars.MONGODB_INITDB_HOSTNAME }}" >> .env
          "MONGODB_INITDB_PORT=${{ vars.MONGODB_INITDB_PORT }}" >> .env

      # Step 2: Set up Docker manually (Docker is already pre-installed on ubuntu-latest)
      - name: Set up Docker
        run: sudo apt-get update && sudo apt-get install -y docker

      # Step 3: Set up Docker Compose
      - name: Set up Docker Compose
        run: sudo apt-get install -y docker-compose

      # Step 4: Build and Start Docker Compose with secrets as environment variables
      - name: Build and Start Docker Compose
        run: |
          docker-compose up --build -d

      # Step 5: Run any commands you want (e.g., tests)
      - name: Run Tests
        run: |
          docker exec nusci-backend npm test

      # Step 6: Tear down the services after the job is done
      - name: Tear Down Docker Compose
        if: always()
        run: docker-compose down
